import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "EULA — David",
  description: "End-User License Agreement for David",
};

export default function EulaPage() {
  return (
    <>
      <h1>End-User License Agreement</h1>
      <p>Last updated: February 10, 2026</p>

      <p>
        Please read this End-User License Agreement carefully before using
        David.
      </p>

      <h2>Interpretation and Definitions</h2>
      <p>For the purposes of this Agreement:</p>
      <ul>
        <li>
          <strong>&ldquo;Agreement&rdquo;</strong> means this End-User License
          Agreement that forms the entire agreement between You and the Company
          regarding the use of the Service.
        </li>
        <li>
          <strong>&ldquo;Service&rdquo;</strong> means the David AI messaging
          assistant, an iMessage-based conversational AI service operated by the
          Company.
        </li>
        <li>
          <strong>&ldquo;Company&rdquo;</strong> (referred to as &ldquo;the
          Company&rdquo;, &ldquo;We&rdquo;, &ldquo;Us&rdquo; or
          &ldquo;Our&rdquo;) refers to Manaflow.
        </li>
        <li>
          <strong>&ldquo;Content&rdquo;</strong> refers to text messages,
          responses, and other information processed or generated by the
          Service.
        </li>
        <li>
          <strong>&ldquo;Country&rdquo;</strong> refers to the United States.
        </li>
        <li>
          <strong>&ldquo;You&rdquo;</strong> means the individual accessing or
          using the Service.
        </li>
      </ul>

      <h2>Acknowledgment</h2>
      <p>
        By sending a text message to the Service or accessing the Site, You are
        agreeing to be bound by the terms of this Agreement. If You do not
        agree, do not use the Service.
      </p>
      <p>
        The Service is licensed, not sold, to You by the Company for use
        strictly in accordance with the terms of this Agreement.
      </p>

      <h2>License</h2>

      <h3>Scope of License</h3>
      <p>
        The Company grants You a revocable, non-exclusive, non-transferable,
        limited license to access and use the Service strictly in accordance
        with this Agreement, for your personal use.
      </p>

      <h3>License Restrictions</h3>
      <p>You agree not to, and You will not permit others to:</p>
      <ul>
        <li>
          Use the Service for any unlawful, harassing, abusive, or fraudulent
          purpose
        </li>
        <li>
          Attempt to reverse engineer, probe, or exploit the Service&rsquo;s AI
          systems or infrastructure
        </li>
        <li>
          Use the Service to generate spam, bulk messages, or automated content
          for distribution
        </li>
        <li>
          Sublicense, sell, or otherwise commercially exploit access to the
          Service
        </li>
      </ul>

      <h2>Intellectual Property</h2>
      <p>
        The Service, including all copyrights, patents, trademarks, trade
        secrets and other intellectual property rights, is and shall remain the
        sole and exclusive property of the Company.
      </p>
      <p>
        You retain ownership of the messages you send to the Service.
        AI-generated responses are provided for your personal use.
      </p>

      <h2>Modifications and Updates</h2>
      <p>
        The Company reserves the right to modify, suspend or discontinue the
        Service at any time, with or without notice and without liability to
        You.
      </p>
      <p>
        The Company may update the Service&rsquo;s capabilities, features, or
        AI models at any time. You agree that all updates are subject to the
        terms of this Agreement.
      </p>

      <h2>Third-Party Services</h2>
      <p>
        The Service integrates with third-party services including messaging
        infrastructure providers, cloud hosting providers, AI model providers,
        and Google APIs (Calendar, Gmail, Contacts). You acknowledge that the
        Company shall not be responsible for any third-party services, including
        their accuracy, completeness, or quality.
      </p>

      <h2>Term and Termination</h2>
      <p>
        This Agreement shall remain in effect until terminated by You or the
        Company. The Company may terminate this Agreement at any time for any
        reason.
      </p>
      <p>
        This Agreement will terminate immediately if you fail to comply with any
        provision. You may also terminate by ceasing to use the Service.
      </p>
      <p>
        Upon termination, You shall cease all use of the Service. You may
        request deletion of your data by contacting us.
      </p>

      <h2>No Warranties</h2>
      <p>
        The Service is provided &ldquo;AS IS&rdquo; and &ldquo;AS
        AVAILABLE&rdquo; without warranty of any kind. The Company expressly
        disclaims all warranties, whether express, implied, statutory or
        otherwise, including all implied warranties of merchantability, fitness
        for a particular purpose, title and non-infringement.
      </p>
      <p>
        The Company does not warrant that AI-generated responses will be
        accurate, complete, or error-free. The Service is not a substitute for
        professional advice.
      </p>
      <p>
        Some jurisdictions do not allow the exclusion of certain types of
        warranties, so some of the above exclusions may not apply to You.
      </p>

      <h2>Limitation of Liability</h2>
      <p>
        The entire liability of the Company under this Agreement shall be
        limited to the amount actually paid by You for the Service, or 100 USD
        if You haven&rsquo;t purchased anything.
      </p>
      <p>
        To the maximum extent permitted by law, in no event shall the Company be
        liable for any special, incidental, indirect, or consequential damages
        whatsoever.
      </p>

      <h2>Indemnification</h2>
      <p>
        You agree to indemnify and hold the Company harmless from any claim or
        demand, including reasonable attorneys&rsquo; fees, due to or arising
        out of your use of the Service or violation of this Agreement.
      </p>

      <h2>Severability and Waiver</h2>
      <p>
        If any provision of this Agreement is held to be unenforceable, it will
        be changed and interpreted to accomplish its objectives to the greatest
        extent possible, and the remaining provisions will continue in full
        force and effect.
      </p>

      <h2>Governing Law</h2>
      <p>
        The laws of the United States, excluding conflicts of law rules, shall
        govern this Agreement and your use of the Service.
      </p>

      <h2>Changes to This Agreement</h2>
      <p>
        The Company reserves the right to modify this Agreement at any time. If
        a revision is material, we will provide at least 30 days&rsquo; notice.
        By continuing to use the Service after revisions become effective, You
        agree to be bound by the revised terms.
      </p>

      <h2>Contact Us</h2>
      <p>If you have any questions about this Agreement:</p>
      <ul>
        <li>
          Email us at{" "}
          <a href="mailto:founders@manaflow.com">founders@manaflow.com</a>
        </li>
      </ul>
    </>
  );
}
